export function injectStyles() {
  var css = [
    /* Custom properties */
    ':root{--d2c-navy:#003b70;--d2c-navy-dark:#002a52;--d2c-blue:#0066cc;--d2c-blue-light:#e8f0fe;--bg:#f5f7fa;--surface:#fff;--border:#e2e8f0;--border-dark:#c4cdd6;--text:#1a2a3a;--text-muted:#64748b;--text-light:#94a3b8;--success:#10b981;--warning:#f59e0b;--danger:#ef4444;--info:#3b82f6;--header-height:95px;--content-max:1200px;--font:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;--mono:"SFMono-Regular",Consolas,"Liberation Mono",Menlo,monospace;--r-sm:4px;--r-md:6px;--r-lg:8px;--r-xl:12px;--shadow-sm:0 1px 3px rgba(0,0,0,.07);--shadow-md:0 4px 12px rgba(0,0,0,.08);--shadow-lg:0 8px 28px rgba(0,0,0,.13);--t:.15s ease}',

    /* Reset & utilities */
    '*,*::before,*::after{box-sizing:border-box}',
    'body{font-family:var(--font);font-size:14px;line-height:1.6;color:var(--text);background:var(--bg);-webkit-font-smoothing:antialiased}',
    'a{color:var(--d2c-blue);transition:color var(--t)}a:hover{color:var(--d2c-navy);text-decoration:none}',
    '.d-none{display:none!important}.d-block{display:block!important}.d-flex{display:flex!important}.d-inline-block{display:inline-block!important}',
    '.pull-left{float:left!important}.pull-right{float:right!important}.hidden{display:none!important}.clearfix::after{content:"";display:table;clear:both}',
    '.fix-row-bootstrap{margin-left:0!important;margin-right:0!important}.bottom-zero{margin-bottom:0!important}',
    '.text-center{text-align:center!important}.text-right{text-align:right!important}.text-left{text-align:left!important}',
    '.text-muted{color:var(--text-muted)!important}.text-danger{color:var(--danger)!important}.text-success{color:var(--success)!important}',
    '.fw-bold,.font-weight-bold{font-weight:600!important}.small,small{font-size:12px!important}',
    '.mt-0{margin-top:0!important}.mt-1{margin-top:4px!important}.mt-2{margin-top:8px!important}.mt-3{margin-top:16px!important}',
    '.mb-0{margin-bottom:0!important}.mb-1{margin-bottom:4px!important}.mb-2{margin-bottom:8px!important}.mb-3{margin-bottom:16px!important}',

    /* Centered layout — sidebar hidden, content centered */
    '#wrapper{width:100%!important;max-width:none!important;overflow:visible!important;margin:0!important}',
    '.navbar-default.sidebar,div.navbar-default.sidebar{display:none!important}',
    '#page-wrapper{margin-left:0!important;min-height:calc(100vh - var(--header-height))!important;background:var(--bg)!important;padding:0!important}',
    '#content{width:auto!important;max-width:var(--content-max)!important;margin:0 auto!important;padding:28px 40px!important;box-sizing:border-box!important}',
    '@media(max-width:767px){#content{padding:16px!important}}',

    /* Sticky header */
    'nav.navbar.navbar-default{position:sticky!important;top:0!important;z-index:1030!important;background:var(--surface)!important;border:none!important;border-bottom:none!important;box-shadow:var(--shadow-sm)!important;border-radius:0!important;margin-bottom:0!important;width:100%!important;overflow:visible!important}',
    '#topRight{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:8px!important;padding:6px 20px!important;background:var(--surface)!important;border-bottom:1px solid var(--border)!important;float:none!important;width:100%!important;box-sizing:border-box!important;position:relative!important}',
    'ul.navbar-top-links,.navbar-top-links{float:none!important;margin:0!important;display:flex!important;align-items:center!important;gap:2px!important}',
    '.navbar-top-links>li{display:inline-flex!important;align-items:center!important}',
    '.navbar-top-links>li>a{padding:5px 10px!important;color:var(--text-muted)!important;font-size:13px!important;border-radius:var(--r-md)!important;display:flex!important;align-items:center!important;gap:5px!important;transition:background var(--t),color var(--t)!important}',
    '.navbar-top-links>li>a:hover{background:var(--bg)!important;color:var(--text)!important}',
    /* Hide dealer selector — command palette replaces it */
    '#dealername,.top-dropdown.brandname{display:none!important}',
    /* Hide original "Need help?" button — replaced by our custom help menu */
    '#needHelp,li:has(#needHelp){display:none!important}',
    /* Hide website / help links — not needed with command palette */
    '#header_website_link{display:none!important}',

    /* Top nav bar — explicit height chain so links fill correctly */
    '.topnav,div.topnav#desktopnav{width:100%!important;background:linear-gradient(180deg,var(--d2c-navy) 0%,var(--d2c-navy-dark) 100%)!important;height:44px!important;min-height:44px!important;border-bottom:2px solid rgba(0,102,204,.45)!important;display:flex!important;align-items:stretch!important;overflow:visible!important;padding:0!important}',
    '.topnav ul{margin:0 auto!important;padding:0!important;height:100%!important;display:flex!important;align-items:stretch!important;list-style:none!important;float:none!important;justify-content:center!important}',
    '.topnav ul li{float:none!important;list-style:none!important;height:100%!important;display:flex!important;align-items:stretch!important}',
    '.topnav ul li a{display:flex!important;align-items:center!important;padding:0 16px!important;height:100%!important;font-size:13px!important;font-weight:500!important;color:rgba(255,255,255,.85)!important;text-decoration:none!important;letter-spacing:.3px!important;border-bottom:2px solid transparent!important;transition:background var(--t),color var(--t),border-color var(--t)!important;white-space:nowrap!important}',
    '.topnav ul li a:hover{background:rgba(255,255,255,.1)!important;color:#fff!important;border-bottom-color:rgba(255,255,255,.3)!important}',
    '.topnav ul li.active>a,.topnav ul li.open>a{background:rgba(255,255,255,.12)!important;color:#fff!important;border-bottom-color:#5aabff!important}',

    /* Sidebar — hidden (command palette replaces sidebar navigation) */
    '.menu_connected_users{display:none!important}',

    /* Page headers */
    '#content h1{font-size:22px!important;font-weight:600!important;color:var(--text)!important;margin:0 0 24px!important;padding-bottom:16px!important;border-bottom:2px solid var(--border)!important;line-height:1.3!important}',
    '#content h2{font-size:18px!important;font-weight:600!important;color:var(--text)!important;margin:0 0 16px!important}',
    '#content h3{font-size:15px!important;font-weight:600!important;color:var(--text)!important;margin:0 0 12px!important}',

    /* Expandable sections */
    '#content h2.expandablesection{background:var(--d2c-navy)!important;background-image:none!important;color:#fff!important;padding:14px 20px 14px 48px!important;margin:20px 0 0!important;border-radius:var(--r-lg) var(--r-lg) 0 0!important;font-size:14px!important;font-weight:600!important;cursor:pointer!important;user-select:none!important;transition:background var(--t)!important;border:none!important;position:relative!important;display:flex!important;align-items:center!important}',
    '#content h2.expandablesection:hover{background:#004d90!important}',
    '#content h2.expandablesection.closed{border-radius:var(--r-lg)!important;margin-bottom:8px!important;background:#4a5568!important}',
    '#content h2.expandablesection.closed:hover{background:#2d3748!important}',
    '#content h2.expandablesection::before{content:"\\2212"!important;position:absolute!important;left:16px!important;font-size:20px!important;font-weight:300!important;line-height:1!important;color:rgba(255,255,255,.6)!important;background-image:none!important;width:20px!important;text-align:center!important}',
    '#content h2.expandablesection.closed::before{content:"+"!important}',
    '#content h2.expandablesection .expandableHeaderText,#content h2.expandablesection .first{color:#fff!important;font-weight:600!important}',
    /* Checkboxes and position-selects in section headers — hide when collapsed, show when open */
    '#content h2.expandablesection.closed input[type="checkbox"],#content h2.expandablesection.closed select{display:none!important}',
    '#content h2.expandablesection input[type="checkbox"]{accent-color:#fff!important;flex-shrink:0!important;width:15px!important;height:15px!important;margin:0 8px 0 0!important;cursor:pointer!important;vertical-align:middle!important}',
    /* Native selects (position dropdowns) embedded in section headers */
    '#content h2.expandablesection select{background:#002a52!important;border:1px solid rgba(255,255,255,.35)!important;color:#fff!important;border-radius:var(--r-md)!important;height:28px!important;padding:2px 8px!important;font-size:12px!important;font-family:var(--font)!important;cursor:pointer!important;box-shadow:none!important;margin-left:10px!important;flex-shrink:0!important;appearance:auto!important;-webkit-appearance:auto!important}',
    '#content h2.expandablesection select option{background:#1a2a3a!important;color:#fff!important}',
    '#content h2.expandablesection select:focus{outline:1px solid rgba(255,255,255,.6)!important;box-shadow:none!important}',
    '#content h2.expandablesection+div,#content h2.expandablesection+table{border:1px solid var(--border)!important;border-top:none!important;border-radius:0 0 var(--r-lg) var(--r-lg)!important;background:var(--surface)!important;padding:24px!important;margin-bottom:8px!important}',
    '#content h5.expandablesection{background:#f1f5f9!important;background-image:none!important;color:var(--text)!important;padding:10px 16px 10px 36px!important;margin:16px 0 0!important;border-radius:var(--r-md) var(--r-md) 0 0!important;font-size:13px!important;font-weight:600!important;cursor:pointer!important;user-select:none!important;transition:background var(--t)!important;border:1px solid var(--border)!important;border-bottom:none!important;position:relative!important;display:flex!important;align-items:center!important}',
    '#content h5.expandablesection:hover{background:#e8eef6!important}',
    '#content h5.expandablesection.closed{border-radius:var(--r-md)!important;border:1px solid var(--border)!important;margin-bottom:8px!important;background:#f8fafc!important}',
    '#content h5.expandablesection::before{content:"\\2212"!important;position:absolute!important;left:12px!important;font-size:14px!important;color:var(--text-muted)!important;background-image:none!important}',
    '#content h5.expandablesection.closed::before{content:"+"!important}',
    '#content h5.expandablesection+div,#content h5.expandablesection+table{border:1px solid var(--border)!important;border-top:none!important;border-radius:0 0 var(--r-md) var(--r-md)!important;background:var(--surface)!important;padding:16px!important;margin-bottom:8px!important}',

    /* Forms */
    '.form-group{margin-bottom:16px!important}',
    '.form-group label,label{font-size:13px!important;font-weight:500!important;color:var(--text)!important;margin-bottom:4px!important;display:block!important}',
    '.form-control{height:36px!important;padding:6px 12px!important;font-size:13px!important;color:var(--text)!important;background:var(--surface)!important;border:1px solid var(--border-dark)!important;border-radius:var(--r-md)!important;box-shadow:none!important;transition:border-color var(--t),box-shadow var(--t)!important;line-height:1.5!important;width:100%!important}',
    '.form-control:focus{border-color:var(--d2c-blue)!important;box-shadow:0 0 0 3px rgba(0,102,204,.12)!important;outline:none!important}',
    '.form-control:disabled,.form-control[readonly]{background:var(--bg)!important;color:var(--text-muted)!important;cursor:not-allowed!important}',
    'textarea.form-control{height:auto!important;min-height:80px!important;resize:vertical!important}',
    'input[data-editable],select[data-editable],textarea[data-editable]{border-color:#92c5f8!important;background:#eff8ff!important}',
    '.has-warning .form-control{border-color:var(--warning)!important}.has-error .form-control{border-color:var(--danger)!important}',

    /* Buttons */
    '.btn{display:inline-flex!important;align-items:center!important;justify-content:center!important;padding:7px 16px!important;font-size:13px!important;font-weight:500!important;line-height:1.4!important;border-radius:var(--r-md)!important;border:1px solid transparent!important;cursor:pointer!important;transition:all var(--t)!important;text-decoration:none!important;white-space:nowrap!important;box-shadow:none!important;gap:6px!important;font-family:var(--font)!important}',
    '.btn:focus{outline:none!important;box-shadow:0 0 0 3px rgba(0,59,112,.2)!important}',
    '.btn-default{background:var(--surface)!important;border-color:var(--border-dark)!important;color:var(--text)!important}',
    '.btn-default:hover{background:var(--bg)!important;border-color:#a0aec0!important}',
    '.btn-primary{background:var(--d2c-navy)!important;border-color:var(--d2c-navy)!important;color:#fff!important}',
    '.btn-primary:hover,.btn-primary:focus{background:#004d90!important;border-color:#004d90!important;color:#fff!important}',
    '.btn-success{background:var(--success)!important;border-color:var(--success)!important;color:#fff!important}',
    '.btn-danger{background:var(--danger)!important;border-color:var(--danger)!important;color:#fff!important}',
    '.btn-warning{background:var(--warning)!important;border-color:var(--warning)!important;color:#fff!important}',
    '.btn-info{background:var(--info)!important;border-color:var(--info)!important;color:#fff!important}',
    '.btn-info:hover{background:#2563eb!important;border-color:#2563eb!important;color:#fff!important}',
    '.btn-link{background:none!important;border-color:transparent!important;color:var(--d2c-blue)!important;padding:7px 8px!important;box-shadow:none!important}',
    '.btn-sm{padding:4px 10px!important;font-size:12px!important}.btn-lg{padding:10px 20px!important;font-size:15px!important}.btn-xs{padding:2px 8px!important;font-size:11px!important}',
    '.btn[style*="background"]{color:#fff!important}',
    '.btn-block{width:100%!important;display:flex!important}',
    /* D2C custom button classes (not Bootstrap) */
    '.button,.buttonSmall,input.buttonSmall,a.buttonSmall{display:inline-flex!important;align-items:center!important;justify-content:center!important;padding:6px 16px!important;font-size:13px!important;font-weight:500!important;color:#fff!important;background:var(--d2c-navy)!important;border:none!important;border-radius:var(--r-md)!important;cursor:pointer!important;text-decoration:none!important;font-family:var(--font)!important;transition:background var(--t)!important;white-space:nowrap!important}',
    /* Respect platform-set display:none on .button elements (e.g. #btnAddContact hidden during update mode) */
    '.button[style*="display:none"],.button[style*="display: none"]{display:none!important}',
    '.button:hover,.buttonSmall:hover{background:#004d90!important;color:#fff!important}',
    '.buttonSmall{padding:4px 10px!important;font-size:12px!important}',
    /* Inline margin-right:20% on D2C action buttons breaks in full-width layout — reset it */
    '#content input.buttonSmall[style]{margin-right:0!important}',
    /* Save button — lives inside #d2c-right-panel below section TOC */
    '#d2c-floating-save{flex-shrink:0!important;width:100%!important;padding:10px 0!important;font-size:13px!important;font-weight:600!important;color:#fff!important;background:var(--d2c-blue)!important;border:1px solid var(--d2c-blue)!important;border-radius:var(--r-lg)!important;cursor:pointer!important;box-shadow:var(--shadow-md)!important;font-family:var(--font)!important;transition:background var(--t),color var(--t),border-color var(--t)!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:8px!important}',
    '#d2c-floating-save:hover{background:#0052a3!important;border-color:#0052a3!important;color:#fff!important}',
    '#d2c-floating-save .fa{font-size:14px!important}',

    /* Tables */
    '.table{width:100%!important;border-collapse:collapse!important;margin-bottom:16px!important;font-size:13px!important}',
    '.table>thead>tr>th{padding:10px 12px!important;background:var(--bg)!important;border-bottom:2px solid var(--border-dark)!important;color:var(--text-muted)!important;font-weight:600!important;font-size:12px!important;text-transform:uppercase!important;letter-spacing:.5px!important;vertical-align:bottom!important;text-align:left!important}',
    '.table>tbody>tr>td,.table>tbody>tr>th{padding:10px 12px!important;border-top:1px solid var(--border)!important;vertical-align:middle!important;color:var(--text)!important}',
    '.table-bordered{border:1px solid var(--border)!important}',
    '.table-bordered>thead>tr>th,.table-bordered>tbody>tr>td{border:1px solid var(--border)!important}',
    '.table-striped>tbody>tr:nth-child(odd)>td{background:#f8fafc!important}',
    '.table-hover>tbody>tr:hover>td{background:var(--d2c-blue-light)!important}',
    'td{padding:6px 10px!important;vertical-align:top!important}',

    /* Panels */
    '.panel{background:var(--surface)!important;border:1px solid var(--border)!important;border-radius:var(--r-lg)!important;box-shadow:var(--shadow-sm)!important;margin-bottom:20px!important}',
    '.panel-default>.panel-heading{background:var(--bg)!important;border-bottom:1px solid var(--border)!important;color:var(--text)!important;border-radius:var(--r-lg) var(--r-lg) 0 0!important;padding:12px 16px!important;font-weight:600!important;font-size:14px!important}',
    '.panel-body{padding:16px!important}.panel-footer{background:var(--bg)!important;border-top:1px solid var(--border)!important;padding:12px 16px!important}',

    /* Alerts */
    '.alert{padding:12px 16px!important;border-radius:var(--r-md)!important;border:1px solid transparent!important;font-size:13px!important;margin-bottom:16px!important}',
    '.alert-success{background:#d1fae5!important;border-color:#a7f3d0!important;color:#065f46!important}',
    '.alert-warning{background:#fef3c7!important;border-color:#fde68a!important;color:#92400e!important}',
    '.alert-danger{background:#fee2e2!important;border-color:#fca5a5!important;color:#991b1b!important}',
    '.alert-info{background:#dbeafe!important;border-color:#bfdbfe!important;color:#1e40af!important}',

    /* Modals */
    '.modal{position:fixed!important;top:0!important;right:0!important;bottom:0!important;left:0!important;z-index:1050!important;overflow-x:hidden!important;overflow-y:auto!important}',
    '.modal-dialog{width:600px!important;max-width:90vw!important;background:var(--surface)!important;border-radius:var(--r-xl)!important;overflow:hidden!important;box-shadow:var(--shadow-lg)!important;margin:0 auto!important}',
    '.modal-dialog.modal-lg{width:900px!important}.modal-dialog.modal-sm{width:400px!important}',
    '.modal-header{padding:20px 24px!important;border-bottom:1px solid var(--border)!important;display:flex!important;align-items:center!important;justify-content:space-between!important}',
    '.modal-title{font-size:16px!important;font-weight:600!important;color:var(--text)!important;margin:0!important}',
    '.modal-body{padding:24px!important;max-height:65vh!important;overflow-y:auto!important}',
    '.modal-footer{padding:16px 24px!important;border-top:1px solid var(--border)!important;display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:8px!important;background:var(--bg)!important}',
    '.modal-backdrop.in{background:rgba(0,0,0,.5)!important}',

    /* Collapse */
    '.collapsing{position:relative!important;height:0!important;overflow:hidden!important;transition:height .2s ease!important}',

    /* Bootstrap Select */
    '.bootstrap-select .btn-default{background:var(--surface)!important;border:1px solid var(--border-dark)!important;color:var(--text)!important;border-radius:var(--r-md)!important;padding:6px 10px!important;font-size:13px!important;height:36px!important;display:flex!important;align-items:center!important;width:100%!important;text-align:left!important;font-family:var(--font)!important}',
    '.bootstrap-select .btn-default:hover{background:var(--bg)!important;border-color:var(--d2c-blue)!important}',
    '.bootstrap-select.open .btn-default{border-color:var(--d2c-blue)!important;box-shadow:0 0 0 3px rgba(0,102,204,.12)!important}',
    '.bootstrap-select .filter-option{display:flex!important;align-items:center!important;gap:6px!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important;flex:1!important}',
    '.bootstrap-select .dropdown-menu .inner>li>a{padding:8px 12px!important;display:flex!important;align-items:center!important;gap:8px!important}',
    '.bs-searchbox{padding:8px!important;border-bottom:1px solid var(--border)!important}',
    '.bs-searchbox input{width:100%!important;padding:6px 10px!important;border:1px solid var(--border-dark)!important;border-radius:var(--r-sm)!important;font-size:13px!important;outline:none!important}',

    /* Dropdowns */
    '.dropdown-menu{background:var(--surface)!important;border:1px solid var(--border)!important;border-radius:var(--r-lg)!important;box-shadow:var(--shadow-lg)!important;padding:6px!important;min-width:180px!important;font-size:13px!important;z-index:1050!important}',
    '.dropdown-menu>li>a{display:block!important;padding:7px 12px!important;color:var(--text)!important;border-radius:var(--r-sm)!important;text-decoration:none!important;transition:background var(--t)!important;white-space:nowrap!important}',
    '.dropdown-menu>li>a:hover{background:var(--bg)!important;color:var(--d2c-navy)!important}',
    '.dropdown-menu>li.active>a{background:var(--d2c-blue-light)!important;color:var(--d2c-navy)!important}',
    '.dropdown-menu .divider{height:1px!important;background:var(--border)!important;margin:6px!important}',

    /* Nav tabs */
    '.nav-tabs{border-bottom:2px solid var(--border)!important;margin-bottom:20px!important;padding:0!important;list-style:none!important;display:flex!important;gap:4px!important}',
    '.nav-tabs>li>a{display:block!important;padding:8px 16px!important;font-size:13px!important;font-weight:500!important;color:var(--text-muted)!important;border:1px solid transparent!important;border-bottom:none!important;border-radius:var(--r-md) var(--r-md) 0 0!important;text-decoration:none!important;margin-bottom:-2px!important;transition:color var(--t),background var(--t)!important}',
    '.nav-tabs>li>a:hover{color:var(--text)!important;background:var(--bg)!important;border-color:var(--border)!important}',
    '.nav-tabs>li.active>a{color:var(--d2c-navy)!important;background:var(--surface)!important;border-color:var(--border)!important;border-bottom-color:var(--surface)!important;font-weight:600!important}',

    /* Misc */
    '.well{background:var(--bg)!important;border:1px solid var(--border)!important;border-radius:var(--r-lg)!important;box-shadow:none!important;padding:16px!important}',
    '.progress{background:var(--bg)!important;border-radius:var(--r-sm)!important;height:8px!important;box-shadow:none!important;overflow:hidden!important;margin-bottom:8px!important}',
    '.progress-bar{background:var(--d2c-navy)!important}',
    '.badge{display:inline-flex!important;align-items:center!important;justify-content:center!important;padding:2px 8px!important;font-size:11px!important;font-weight:600!important;border-radius:20px!important;background:var(--d2c-navy)!important;color:#fff!important;min-width:20px!important}',
    '.close{float:right!important;font-size:18px!important;font-weight:600!important;line-height:1!important;color:inherit!important;opacity:.5!important;background:none!important;border:none!important;cursor:pointer!important;padding:2px 6px!important}',
    '.close:hover{opacity:.85!important}',
    '#saveLockScreen{position:fixed!important;top:0!important;left:0!important;width:100%!important;height:100%!important;background:rgba(255,255,255,.7)!important;z-index:9999!important}',

    /* JS-injected enhancement elements */
    '#d2c-right-panel{position:fixed!important;right:16px!important;top:120px!important;width:196px!important;max-height:calc(100vh - 150px)!important;display:flex!important;flex-direction:column!important;gap:8px!important;z-index:1025!important}',
    '#d2c-section-toc{flex:1!important;min-height:0!important;overflow-y:auto!important;background:var(--surface)!important;border:1px solid var(--border)!important;border-radius:var(--r-lg)!important;box-shadow:var(--shadow-md)!important;font-size:12px!important;scrollbar-width:thin!important}',
    '#d2c-section-toc.d2c-toc-minimized .d2c-toc-list,#d2c-section-toc.d2c-toc-minimized .d2c-toc-actions{display:none!important}',
    '.d2c-toc-header{padding:9px 12px!important;font-weight:700!important;font-size:11px!important;color:var(--d2c-navy)!important;border-bottom:1px solid var(--border)!important;cursor:pointer!important;user-select:none!important;text-transform:uppercase!important;letter-spacing:.5px!important;display:flex!important;align-items:center!important;justify-content:space-between!important}',
    '.d2c-toc-actions{padding:6px 8px!important;display:flex!important;gap:4px!important;border-bottom:1px solid var(--border)!important}',
    '.d2c-toc-btn{flex:1!important;padding:3px 6px!important;font-size:10px!important;border:1px solid var(--border)!important;border-radius:var(--r-sm)!important;background:var(--bg)!important;color:var(--text-muted)!important;cursor:pointer!important;text-align:center!important;transition:background var(--t)!important;font-family:var(--font)!important}',
    '.d2c-toc-btn:hover{background:var(--border)!important;color:var(--text)!important}',
    '.d2c-toc-list{list-style:none!important;margin:0!important;padding:4px 0!important}',
    '.d2c-toc-item a{display:block!important;padding:5px 12px!important;color:var(--text-muted)!important;text-decoration:none!important;border-left:2px solid transparent!important;transition:all var(--t)!important;line-height:1.4!important;font-size:11px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}',
    '.d2c-toc-item a:hover{background:var(--bg)!important;color:var(--d2c-navy)!important}',
    '.d2c-toc-item a.d2c-toc-active{border-left-color:var(--d2c-navy)!important;color:var(--d2c-navy)!important;font-weight:600!important;background:var(--d2c-blue-light)!important}',
    '#d2c-palette-overlay{position:fixed!important;inset:0!important;background:rgba(0,0,0,.5)!important;z-index:100000!important;justify-content:center!important;align-items:flex-start!important;padding-top:14vh!important;backdrop-filter:blur(3px)!important}',
    '#d2c-palette{width:580px!important;max-width:90vw!important;background:var(--surface)!important;border-radius:var(--r-xl)!important;box-shadow:0 24px 60px rgba(0,0,0,.28)!important;overflow:hidden!important}',
    '#d2c-palette-input{width:100%!important;padding:18px 20px!important;border:none!important;border-bottom:1px solid var(--border)!important;font-size:16px!important;font-family:var(--font)!important;outline:none!important;box-sizing:border-box!important;color:var(--text)!important;background:transparent!important}',
    '#d2c-palette-input::placeholder{color:var(--text-light)!important}',
    '#d2c-palette-results{max-height:300px!important;overflow-y:auto!important;padding:6px 0!important}',
    '.d2c-palette-item{padding:10px 16px!important;cursor:pointer!important;display:flex!important;align-items:center!important;gap:10px!important;font-size:13px!important;color:var(--text)!important;transition:background .08s!important}',
    '.d2c-palette-item:hover,.d2c-palette-item.d2c-palette-active{background:var(--d2c-blue-light)!important}',
    '.d2c-palette-item .fa{color:var(--text-light)!important;width:20px!important;text-align:center!important;flex-shrink:0!important}',
    '.d2c-palette-title{flex:1!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}',
    '.d2c-palette-type{font-size:10px!important;padding:2px 7px!important;border-radius:20px!important;font-weight:600!important;text-transform:uppercase!important;letter-spacing:.4px!important;flex-shrink:0!important}',
    '.d2c-pt-page{background:#d1fae5!important;color:#065f46!important}.d2c-pt-dealer{background:var(--d2c-blue-light)!important;color:var(--d2c-navy)!important}.d2c-pt-nav{background:#fef3c7!important;color:#92400e!important}',
    '.d2c-palette-empty{padding:32px 20px!important;text-align:center!important;color:var(--text-light)!important;font-size:14px!important}',
    '#d2c-palette-footer{padding:8px 16px!important;border-top:1px solid var(--border)!important;background:var(--bg)!important;display:flex!important;gap:16px!important;font-size:11px!important;color:var(--text-light)!important;align-items:center!important}',
    '#d2c-palette-footer kbd{display:inline-block!important;padding:2px 6px!important;border:1px solid var(--border-dark)!important;border-radius:4px!important;background:var(--surface)!important;font-size:10px!important;font-family:var(--mono)!important;color:var(--text-muted)!important;margin-right:2px!important}',
    // Filter bar
    '#d2c-palette-filters{padding:8px 12px 4px!important;border-bottom:1px solid var(--border)!important;display:flex!important;flex-direction:column!important;gap:5px!important}',
    '.d2c-pf-row{display:flex!important;flex-wrap:wrap!important;gap:4px!important;align-items:center!important}',
    '.d2c-pf-label{font-size:10px!important;font-weight:700!important;text-transform:uppercase!important;color:var(--text-light)!important;margin-right:2px!important;white-space:nowrap!important;letter-spacing:.4px!important}',
    '.d2c-pf-pill{display:inline-flex!important;align-items:center!important;gap:3px!important;font-size:11px!important;padding:3px 8px!important;border-radius:20px!important;border:1px solid var(--border-dark)!important;background:transparent!important;color:var(--text-light)!important;cursor:pointer!important;font-family:var(--font)!important;line-height:1.4!important;transition:border-color .1s,color .1s!important}',
    '.d2c-pf-pill:hover{border-color:var(--d2c-navy)!important;color:var(--d2c-navy)!important}',
    '.d2c-pf-pill.d2c-pf-active{background:var(--d2c-navy)!important;color:#fff!important;border-color:var(--d2c-navy)!important}',
    '.d2c-pf-star{font-size:10px!important;opacity:0!important;transition:opacity .1s,color .1s!important;cursor:pointer!important;line-height:1!important;pointer-events:auto!important}',
    '.d2c-pf-pill:hover .d2c-pf-star{opacity:.4!important}',
    '.d2c-pf-pill.d2c-pf-pinned .d2c-pf-star{opacity:1!important;color:#f59e0b!important}',
    '.d2c-pf-pill.d2c-pf-active .d2c-pf-star{color:rgba(255,255,255,.7)!important}',
    '.d2c-pf-pill.d2c-pf-active.d2c-pf-pinned .d2c-pf-star{color:#f59e0b!important}',
    '#d2c-save-indicator{position:fixed!important;bottom:80px!important;right:24px!important;padding:8px 16px!important;border-radius:var(--r-lg)!important;font-size:12px!important;font-weight:500!important;font-family:var(--font)!important;z-index:10001!important;transition:all .25s ease!important;display:flex!important;align-items:center!important;gap:8px!important;box-shadow:var(--shadow-md)!important;pointer-events:none!important}',
    '#d2c-save-indicator.d2c-save-idle{display:none!important}',
    '#d2c-save-indicator.d2c-save-active{background:#fef3c7!important;color:#92400e!important;border:1px solid var(--warning)!important;opacity:1!important}',
    '#d2c-save-indicator.d2c-save-error{background:#fee2e2!important;color:#991b1b!important;border:1px solid var(--danger)!important;opacity:1!important;pointer-events:auto!important}',
    '#d2c-scroll-top{position:fixed!important;bottom:24px!important;right:224px!important;width:36px!important;height:36px!important;border-radius:50%!important;background:var(--d2c-navy)!important;color:#fff!important;border:none!important;cursor:pointer!important;z-index:10001!important;opacity:0!important;transform:translateY(12px)!important;transition:opacity .2s,transform .2s!important;font-size:14px!important;box-shadow:var(--shadow-md)!important;display:flex!important;align-items:center!important;justify-content:center!important;pointer-events:none!important;font-family:var(--font)!important}',
    '#d2c-scroll-top.d2c-st-visible{opacity:1!important;transform:translateY(0)!important;pointer-events:auto!important}',
    '#d2c-scroll-top:hover{background:#004d90!important}',

    /* Floating dealer nav panel (left side) */
    '#d2c-dealer-nav{position:fixed!important;top:120px!important;left:16px!important;width:180px!important;max-height:calc(100vh - 150px)!important;overflow-y:auto!important;background:var(--surface)!important;border:1px solid var(--border)!important;border-radius:var(--r-lg)!important;box-shadow:var(--shadow-md)!important;z-index:1025!important;font-size:12px!important;scrollbar-width:thin!important}',
    '.d2c-dn-header{padding:9px 12px!important;font-weight:700!important;font-size:11px!important;color:var(--d2c-navy)!important;border-bottom:1px solid var(--border)!important;text-transform:uppercase!important;letter-spacing:.5px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}',
    '.d2c-dn-list{list-style:none!important;margin:0!important;padding:4px 0!important}',
    '.d2c-dn-list li a{display:flex!important;align-items:center!important;gap:6px!important;padding:5px 12px!important;color:var(--text-muted)!important;text-decoration:none!important;border-left:2px solid transparent!important;transition:all var(--t)!important;line-height:1.4!important;font-size:12px!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}',
    '.d2c-dn-list li a:hover{background:var(--bg)!important;color:var(--d2c-navy)!important}',
    '.d2c-dn-list li a.d2c-dn-active{border-left-color:var(--d2c-navy)!important;color:var(--d2c-navy)!important;font-weight:600!important;background:var(--d2c-blue-light)!important}',
    '.d2c-dn-list li a .fa{width:14px!important;text-align:center!important;color:var(--text-light)!important;flex-shrink:0!important;font-size:11px!important}',
    '.d2c-dn-list li a.d2c-dn-active .fa{color:var(--d2c-navy)!important}',
    '.d2c-dn-section{padding:6px 12px 3px!important;font-size:10px!important;font-weight:700!important;color:var(--text-muted)!important;text-transform:uppercase!important;letter-spacing:.5px!important;margin-top:4px!important}',
    '.d2c-dn-more{border-top:1px solid var(--border)!important;margin-top:4px!important}',
    '.d2c-dn-more-btn{display:block!important;width:100%!important;padding:6px 12px!important;font-size:11px!important;color:var(--text-muted)!important;background:none!important;border:none!important;cursor:pointer!important;text-align:left!important;font-family:var(--font)!important;transition:color var(--t)!important}',
    '.d2c-dn-more-btn:hover{color:var(--d2c-navy)!important}',

    /* Breadcrumb in header */
    '#d2c-breadcrumb{display:flex!important;align-items:center!important;gap:6px!important;font-size:13px!important;color:var(--text-muted)!important;margin-right:auto!important;min-width:0!important;overflow:hidden!important}',
    '#d2c-breadcrumb span{white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}',
    '#d2c-breadcrumb .d2c-bc-sep{color:var(--text-light)!important;flex-shrink:0!important;font-size:10px!important}',
    '#d2c-breadcrumb .d2c-bc-dealer{font-weight:600!important;color:#fff!important;font-size:1.4rem!important;background:var(--d2c-navy)!important;padding:.5rem 1.2rem!important;border-radius:var(--r-md)!important}',
    '#d2c-breadcrumb .d2c-bc-section{color:var(--text-muted)!important}',
    '#d2c-breadcrumb .d2c-bc-page{color:var(--text)!important;font-weight:500!important}',

    /* Brand nav widget */
    '.d2c-bn-wrapper{display:inline-flex!important;align-items:center!important;gap:3px!important;overflow:visible!important;flex-shrink:0!important;white-space:nowrap!important}',
    '.d2c-bn-arrow{display:inline-flex!important;align-items:center!important;justify-content:center!important;width:22px!important;height:22px!important;padding:0!important;background:var(--d2c-navy)!important;color:#fff!important;border:none!important;border-radius:var(--r-sm)!important;cursor:pointer!important;font-size:16px!important;line-height:1!important;font-family:var(--font)!important;flex-shrink:0!important;transition:background var(--t)!important}',
    '.d2c-bn-arrow:hover{background:#004d90!important}',
    'button.d2c-bn-pill{border:none!important;cursor:pointer!important;font-family:var(--font)!important;transition:background var(--t)!important;line-height:1.4!important}',
    'button.d2c-bn-pill:hover{background:#004d90!important}',
    '.d2c-bn-caret{font-size:10px!important;opacity:.75!important}',
    '.d2c-bn-dropdown{position:fixed!important;z-index:1060!important;background:var(--surface)!important;border:1px solid var(--border)!important;border-radius:var(--r-lg)!important;box-shadow:var(--shadow-lg)!important;padding:4px 0!important;min-width:220px!important;max-height:320px!important;overflow-y:auto!important;list-style:none!important;margin:0!important;display:none!important}',
    '.d2c-bn-dropdown.d2c-bn-open{display:block!important}',
    '.d2c-bn-dropdown-header{padding:6px 14px 5px!important;font-size:10px!important;font-weight:700!important;text-transform:uppercase!important;letter-spacing:.6px!important;color:var(--text-muted)!important;pointer-events:none!important;border-bottom:1px solid var(--border)!important;margin-bottom:3px!important}',
    '.d2c-bn-dropdown li a{display:block!important;padding:7px 14px!important;font-size:13px!important;color:var(--text)!important;text-decoration:none!important;transition:background var(--t)!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}',
    '.d2c-bn-dropdown li a:hover{background:var(--d2c-blue-light)!important;color:var(--d2c-navy)!important}',
    '.d2c-bn-dropdown li a.d2c-bn-current{font-weight:600!important;color:var(--d2c-navy)!important;border-left:3px solid var(--d2c-navy)!important;padding-left:11px!important}',
    '.d2c-bn-dropdown li a.d2c-bn-current:hover{background:var(--d2c-blue-light)!important}',

    /* Search hint */
    '#d2c-search-hint{flex-shrink:0!important}',
    '#d2c-search-hint>a{display:flex!important;align-items:center!important;gap:6px!important;padding:4px 8px!important;color:var(--text-muted)!important;border-radius:var(--r-md)!important;border:none!important;background:transparent!important;transition:background var(--t),color var(--t)!important;font-size:13px!important;text-decoration:none!important;cursor:pointer!important}',
    '#d2c-search-hint>a:hover{background:var(--bg)!important;color:var(--text)!important}',
    '#d2c-search-hint .fa{font-size:13px!important;color:var(--text-light)!important}',
    '.d2c-hint-label{font-size:13px!important;color:var(--text-muted)!important}',
    '.d2c-hint-kbd{display:inline-block!important;padding:1px 6px!important;border:1px solid var(--border-dark)!important;border-radius:3px!important;font-size:10px!important;font-family:var(--mono)!important;color:var(--text-muted)!important;background:var(--surface)!important;line-height:1.6!important;margin-left:4px!important}',

    /* Version badge + Help button */
    '#d2c-help-btn{position:relative!important;display:inline-flex!important;align-items:center!important;gap:4px!important;flex-shrink:0!important}',
    '#d2c-version-badge{font-size:11px!important;color:var(--text-light)!important;white-space:nowrap!important;padding:2px 0!important;pointer-events:none!important}',
    '#d2c-help-toggle{background:transparent!important;border:none!important;cursor:pointer!important;padding:4px 8px!important;color:var(--text-muted)!important;border-radius:var(--r-md)!important;font-size:13px!important;transition:background var(--t),color var(--t)!important;font-family:var(--font)!important;display:flex!important;align-items:center!important;line-height:1!important}',
    '#d2c-help-toggle:hover{background:var(--bg)!important;color:var(--text)!important}',
    '#d2c-help-toggle .fa{font-size:14px!important}',
    '#d2c-help-dropdown{display:none!important;position:absolute!important;top:calc(100% + 6px)!important;right:0!important;width:260px!important;background:var(--surface)!important;border:1px solid var(--border)!important;border-radius:var(--r-lg)!important;box-shadow:var(--shadow-lg)!important;z-index:1100!important}',
    '#d2c-help-dropdown.d2c-help-open{display:block!important}',
    '.d2c-help-header{padding:12px 14px!important;border-bottom:1px solid var(--border)!important;display:flex!important;flex-direction:column!important;gap:2px!important}',
    '.d2c-help-title{font-size:13px!important;font-weight:600!important;color:var(--text)!important}',
    '.d2c-help-version{font-size:11px!important;color:var(--text-light)!important}',
    '.d2c-help-section{padding:8px 14px 3px!important;font-size:10px!important;font-weight:700!important;color:var(--text-muted)!important;text-transform:uppercase!important;letter-spacing:.5px!important}',
    '.d2c-help-table{width:100%!important;padding:2px 8px 6px!important;border-collapse:collapse!important}',
    '.d2c-help-table td{padding:3px 6px!important;font-size:12px!important;color:var(--text)!important;border:none!important}',
    '.d2c-help-table td:first-child{width:110px!important;white-space:nowrap!important}',
    '.d2c-help-table kbd{display:inline-block!important;padding:2px 5px!important;border:1px solid var(--border-dark)!important;border-radius:4px!important;font-size:10px!important;font-family:var(--mono)!important;color:var(--text-muted)!important;background:var(--bg)!important;line-height:1.6!important}',
    '.d2c-help-list{list-style:none!important;margin:0!important;padding:4px 14px 10px!important}',
    '.d2c-help-list li{font-size:12px!important;color:var(--text-muted)!important;padding:2px 0 2px 10px!important;position:relative!important}',
    '.d2c-help-list li::before{content:"\\00B7"!important;position:absolute!important;left:0!important;color:var(--text-light)!important}',

    /* ── Audit / Save History panel (bottom-right corner) ── */
    '#d2c-audit-wrap{position:fixed!important;bottom:24px!important;right:24px!important;z-index:10002!important;display:flex!important;flex-direction:column!important;align-items:flex-end!important;gap:8px!important;font-family:var(--font)!important}',

    /* Toggle button */
    '#d2c-audit-toggle{display:inline-flex!important;align-items:center!important;gap:6px!important;padding:8px 14px!important;background:var(--d2c-navy)!important;color:#fff!important;border:none!important;border-radius:var(--r-lg)!important;font-size:12px!important;font-weight:500!important;font-family:var(--font)!important;cursor:pointer!important;box-shadow:var(--shadow-md)!important;transition:background var(--t)!important;white-space:nowrap!important}',
    '#d2c-audit-toggle:hover{background:var(--d2c-navy-dark)!important}',
    '#d2c-audit-toggle .fa{font-size:12px!important}',
    '#d2c-al-badge{display:inline-flex!important;align-items:center!important;justify-content:center!important;min-width:16px!important;height:16px!important;padding:0 4px!important;background:#ef4444!important;color:#fff!important;border-radius:999px!important;font-size:10px!important;font-weight:700!important;line-height:1!important;margin-left:2px!important}',

    /* Panel */
    '#d2c-audit-panel{display:none!important;width:300px!important;max-height:380px!important;background:var(--surface)!important;border:1px solid var(--border)!important;border-radius:var(--r-xl)!important;box-shadow:var(--shadow-lg)!important;overflow:hidden!important;flex-direction:column!important}',
    '#d2c-audit-panel.d2c-al-open{display:flex!important}',
    '#d2c-al-header{display:flex!important;align-items:center!important;justify-content:space-between!important;padding:10px 14px!important;border-bottom:1px solid var(--border)!important;background:var(--surface)!important;flex-shrink:0!important}',
    '#d2c-al-title{font-size:13px!important;font-weight:600!important;color:var(--text)!important;display:flex!important;align-items:center!important;gap:6px!important}',
    '#d2c-al-title .fa{color:var(--d2c-navy)!important;font-size:12px!important}',
    '#d2c-al-actions{display:flex!important;align-items:center!important;gap:4px!important}',
    '#d2c-al-clear{padding:2px 8px!important;font-size:11px!important;color:var(--text-muted)!important;background:transparent!important;border:1px solid var(--border)!important;border-radius:var(--r-sm)!important;cursor:pointer!important;font-family:var(--font)!important;transition:background var(--t),color var(--t)!important}',
    '#d2c-al-clear:hover{background:var(--bg)!important;color:var(--danger)!important;border-color:var(--danger)!important}',
    '#d2c-al-close{width:24px!important;height:24px!important;display:flex!important;align-items:center!important;justify-content:center!important;background:transparent!important;border:none!important;cursor:pointer!important;font-size:16px!important;color:var(--text-muted)!important;border-radius:var(--r-sm)!important;line-height:1!important;font-family:var(--font)!important;transition:background var(--t),color var(--t)!important}',
    '#d2c-al-close:hover{background:var(--bg)!important;color:var(--text)!important}',

    /* Entry list */
    '#d2c-al-list{overflow-y:auto!important;flex:1!important;padding:6px 0!important}',
    '.d2c-al-entry{padding:8px 14px!important;border-bottom:1px solid var(--border)!important;transition:background var(--t)!important}',
    '.d2c-al-entry:last-child{border-bottom:none!important}',
    '.d2c-al-entry:hover{background:var(--bg)!important}',
    '.d2c-al-row{display:flex!important;align-items:center!important;justify-content:space-between!important;margin-bottom:2px!important}',
    '.d2c-al-time{font-size:11px!important;color:var(--text-light)!important}',
    '.d2c-al-actions{display:flex!important;align-items:center!important;gap:4px!important}',
    '.d2c-al-check{width:20px!important;height:20px!important;border-radius:50%!important;border:1.5px solid var(--border)!important;background:transparent!important;color:var(--text-light)!important;font-size:12px!important;font-weight:700!important;line-height:1!important;cursor:pointer!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;transition:background var(--t),border-color var(--t),color var(--t)!important;padding:0!important;font-family:var(--font)!important;flex-shrink:0!important}',
    '.d2c-al-check:hover{border-color:#22c55e!important;color:#22c55e!important}',
    '.d2c-al-check.d2c-al-check-done{background:#22c55e!important;border-color:#22c55e!important;color:#fff!important}',
    '.d2c-al-remove{width:18px!important;height:18px!important;border-radius:50%!important;border:none!important;background:transparent!important;color:var(--text-light)!important;font-size:14px!important;line-height:1!important;cursor:pointer!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;transition:background var(--t),color var(--t)!important;padding:0!important;font-family:var(--font)!important;flex-shrink:0!important;opacity:0!important}',
    '.d2c-al-entry:hover .d2c-al-remove{opacity:1!important}',
    '.d2c-al-remove:hover{background:var(--danger)!important;color:#fff!important;opacity:1!important}',
    '.d2c-al-entry.d2c-al-qcd{opacity:.55!important}',
    '.d2c-al-entry.d2c-al-qcd .d2c-al-title{text-decoration:line-through!important;color:var(--text-muted)!important}',
    '.d2c-al-title{font-size:12px!important;color:var(--text)!important;font-weight:500!important;white-space:nowrap!important;overflow:hidden!important;text-overflow:ellipsis!important}',
    '.d2c-al-title.d2c-al-link{cursor:pointer!important;color:var(--d2c-blue)!important}',
    '.d2c-al-title.d2c-al-link:hover{text-decoration:underline!important}',
    '.d2c-al-link-icon{font-size:9px!important;opacity:.6!important}',
    '#d2c-al-badge.d2c-al-badge-clear{background:#16a34a!important}',
    '#d2c-al-badge.d2c-al-badge-clear{font-size:9px!important}',
    '.d2c-al-empty{padding:24px 14px!important;text-align:center!important;font-size:12px!important;color:var(--text-light)!important;white-space:pre-line!important;line-height:1.7!important}',

    /* ── Holiday Hours widget (right panel) ── */
    '#d2c-shortcuts-label{font-size:10px!important;font-weight:700!important;text-transform:uppercase!important;letter-spacing:.6px!important;color:var(--text-light)!important;padding:2px 4px!important}',
    '#d2c-hh-widget{background:var(--surface)!important;border:1px solid var(--border)!important;border-radius:var(--r-lg)!important;box-shadow:var(--shadow-md)!important;overflow:hidden!important;font-size:12px!important;scrollbar-width:thin!important}',
    '#d2c-hh-widget-header{padding:9px 12px!important;font-weight:700!important;font-size:11px!important;color:var(--d2c-navy)!important;border-bottom:1px solid var(--border)!important;cursor:pointer!important;user-select:none!important;text-transform:uppercase!important;letter-spacing:.5px!important;display:flex!important;align-items:center!important;justify-content:space-between!important}',
    '#d2c-hh-widget-header .fa{margin-right:4px!important}',
    '#d2c-hh-widget.d2c-hh-minimized #d2c-hh-widget-header{border-bottom:none!important}',
    '#d2c-hh-widget.d2c-hh-minimized #d2c-hh-widget-body{display:none!important}',
    '#d2c-hh-widget-body{padding:10px!important;display:flex!important;flex-direction:column!important;gap:6px!important}',
    '#d2c-hh-snap-info{font-size:11px!important;color:var(--success)!important;line-height:1.5!important;padding:4px 8px!important;background:#f0fdf4!important;border:1px solid #bbf7d0!important;border-radius:var(--r-sm)!important}',
    '#d2c-hh-snap-info .fa{margin-right:4px!important}',
    '#d2c-hh-snap-date{color:var(--text-muted)!important;font-size:10px!important}',
    '.d2c-hh-btn-widget{width:100%!important;padding:7px 10px!important;font-size:12px!important;font-weight:500!important;border-radius:var(--r-md)!important;border:1px solid var(--border-dark)!important;background:var(--surface)!important;color:var(--text)!important;cursor:pointer!important;font-family:var(--font)!important;display:flex!important;align-items:center!important;justify-content:center!important;gap:5px!important;transition:all var(--t)!important}',
    '.d2c-hh-btn-widget:hover:not(:disabled){background:var(--bg)!important;border-color:#a0aec0!important}',
    '.d2c-hh-btn-widget:disabled{opacity:.45!important;cursor:not-allowed!important}',
    '.d2c-hh-btn-primary-widget{background:var(--d2c-navy)!important;border-color:var(--d2c-navy)!important;color:#fff!important}',
    '.d2c-hh-btn-primary-widget:hover:not(:disabled){background:#004d90!important;border-color:#004d90!important;color:#fff!important}',
    '.d2c-hh-btn-danger-widget{border-color:#fca5a5!important;color:var(--danger)!important}',
    '.d2c-hh-btn-danger-widget:hover:not(:disabled){background:#fef2f2!important;border-color:var(--danger)!important}',

    /* ── Holiday Hours modal overlay ── */
    '#d2c-hh-overlay,#d2c-hh-info-overlay{display:none!important;position:fixed!important;inset:0!important;background:rgba(0,0,0,.55)!important;z-index:10100!important;align-items:center!important;justify-content:center!important;padding:20px!important}',
    '#d2c-hh-overlay[style*="flex"],#d2c-hh-info-overlay[style*="flex"]{display:flex!important}',
    '#d2c-hh-modal,#d2c-hh-info-modal{background:var(--surface)!important;border-radius:var(--r-xl)!important;box-shadow:var(--shadow-lg)!important;width:100%!important;max-width:600px!important;max-height:90vh!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;font-family:var(--font)!important}',
    '#d2c-hh-modal-header{display:flex!important;align-items:center!important;justify-content:space-between!important;padding:14px 18px!important;border-bottom:1px solid var(--border)!important;background:var(--d2c-navy)!important;flex-shrink:0!important}',
    '#d2c-hh-modal-title{font-size:14px!important;font-weight:600!important;color:#fff!important;display:flex!important;align-items:center!important;gap:7px!important}',
    '#d2c-hh-modal-title .fa{font-size:14px!important;opacity:.85!important}',
    '#d2c-hh-modal-close{background:transparent!important;border:none!important;color:rgba(255,255,255,.7)!important;font-size:20px!important;cursor:pointer!important;line-height:1!important;padding:0 4px!important;font-family:var(--font)!important;transition:color var(--t)!important}',
    '#d2c-hh-modal-close:hover{color:#fff!important}',
    '#d2c-hh-modal-body{overflow-y:auto!important;flex:1!important;padding:18px!important;display:flex!important;flex-direction:column!important;gap:14px!important}',
    '#d2c-hh-preset-bar{display:flex!important;align-items:center!important;gap:10px!important;flex-wrap:wrap!important}',
    '#d2c-hh-preset-bar label{font-size:13px!important;font-weight:500!important;color:var(--text)!important;margin:0!important;white-space:nowrap!important}',
    '#d2c-hh-day-sel{height:32px!important;padding:4px 10px!important;font-size:13px!important;color:var(--text)!important;background:var(--surface)!important;border:1px solid var(--border-dark)!important;border-radius:var(--r-md)!important;cursor:pointer!important;flex:1!important;min-width:180px!important}',
    '#d2c-hh-dept-note{font-size:12px!important;color:var(--text-muted)!important;background:var(--d2c-blue-light)!important;border:1px solid #bfdbfe!important;border-radius:var(--r-md)!important;padding:8px 12px!important;display:flex!important;align-items:flex-start!important;gap:7px!important}',
    '#d2c-hh-dept-note .fa{color:var(--d2c-blue)!important;margin-top:1px!important;flex-shrink:0!important}',
    '#d2c-hh-table{width:100%!important;border-collapse:collapse!important;font-size:13px!important}',
    '#d2c-hh-table thead tr th{padding:7px 10px!important;background:var(--bg)!important;border-bottom:2px solid var(--border-dark)!important;color:var(--text-muted)!important;font-size:11px!important;font-weight:700!important;text-transform:uppercase!important;letter-spacing:.4px!important;text-align:left!important}',
    '#d2c-hh-table tbody tr{border-bottom:1px solid var(--border)!important}',
    '#d2c-hh-table tbody tr:last-child{border-bottom:none!important}',
    '#d2c-hh-table tbody td{padding:8px 10px!important;vertical-align:middle!important}',
    '.d2c-hh-day{font-weight:500!important;color:var(--text)!important;white-space:nowrap!important;width:90px!important}',
    '.d2c-hh-closed-cell{white-space:nowrap!important;width:80px!important}',
    '.d2c-hh-closed-label{display:inline-flex!important;align-items:center!important;gap:5px!important;font-size:12px!important;color:var(--text)!important;cursor:pointer!important;margin:0!important;font-weight:400!important}',
    '.d2c-hh-open,.d2c-hh-close{height:30px!important;padding:3px 8px!important;font-size:12px!important;color:var(--text)!important;background:var(--surface)!important;border:1px solid var(--border-dark)!important;border-radius:var(--r-sm)!important;width:100%!important;min-width:110px!important}',
    '.d2c-hh-open:disabled,.d2c-hh-close:disabled{background:var(--bg)!important;color:var(--text-light)!important;cursor:not-allowed!important}',
    '#d2c-hh-table tbody tr:has(.d2c-hh-closed-chk:checked){background:#fef2f2!important;opacity:.85!important}',
    '#d2c-hh-modal-footer{display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:10px!important;padding:14px 18px!important;border-top:1px solid var(--border)!important;flex-shrink:0!important;background:var(--bg)!important}',
    '.d2c-hh-btn-primary{background:var(--d2c-navy)!important;border:1px solid var(--d2c-navy)!important;color:#fff!important;padding:8px 18px!important;font-size:13px!important;font-weight:500!important;border-radius:var(--r-md)!important;cursor:pointer!important;font-family:var(--font)!important;display:inline-flex!important;align-items:center!important;gap:6px!important;transition:background var(--t)!important}',
    '.d2c-hh-btn-primary:hover{background:#004d90!important}',
    '.d2c-hh-btn-secondary{background:var(--surface)!important;border:1px solid var(--border-dark)!important;color:var(--text)!important;padding:8px 18px!important;font-size:13px!important;font-weight:500!important;border-radius:var(--r-md)!important;cursor:pointer!important;font-family:var(--font)!important;transition:background var(--t)!important}',
    '.d2c-hh-btn-secondary:hover{background:var(--bg)!important}',

    /* ── Holiday Hours diff / summary tables ── */
    '.d2c-hh-diff-count{font-size:13px!important;color:var(--text)!important;margin:0 0 10px!important;font-weight:500!important}',
    '.d2c-hh-diff-empty{font-size:13px!important;color:var(--text-muted)!important;text-align:center!important;padding:20px 0!important}',
    '.d2c-hh-diff-table{width:100%!important;border-collapse:collapse!important;font-size:12px!important}',
    '.d2c-hh-diff-table thead th{padding:6px 8px!important;background:var(--bg)!important;border-bottom:2px solid var(--border-dark)!important;color:var(--text-muted)!important;font-size:10px!important;font-weight:700!important;text-transform:uppercase!important;letter-spacing:.4px!important;text-align:center!important;white-space:nowrap!important}',
    '.d2c-hh-diff-table thead th:first-child{text-align:left!important}',
    '.d2c-hh-diff-table tbody tr{border-bottom:1px solid var(--border)!important}',
    '.d2c-hh-diff-table tbody tr:last-child{border-bottom:none!important}',
    '.d2c-hh-diff-table tbody td{padding:6px 8px!important;vertical-align:middle!important;text-align:center!important;color:var(--text)!important}',
    '.d2c-hh-diff-table tbody td.d2c-hh-day{text-align:left!important;font-weight:600!important;white-space:nowrap!important;width:70px!important}',
    '.d2c-hh-diff-closed{color:var(--text-muted)!important;font-style:italic!important}',
    '.d2c-hh-diff-close{display:block!important;color:var(--text-muted)!important;font-size:11px!important}',
    '.d2c-hh-diff-compact .d2c-hh-diff-from{color:var(--danger)!important;text-decoration:line-through!important;font-size:11px!important}',
    '.d2c-hh-diff-compact .d2c-hh-diff-to{color:var(--success)!important;font-weight:500!important;font-size:11px!important}',
    '.d2c-hh-diff-compact .d2c-hh-diff-arrow{color:var(--text-light)!important;font-size:14px!important;padding:0 2px!important}',
    '#d2c-hh-info-modal{max-width:720px!important}',

    /* ── Promo Manager widget (right panel, /sites/promotions only) ── */
    '#d2c-pm-widget{background:var(--surface)!important;border:1px solid var(--border)!important;border-radius:var(--r-lg)!important;box-shadow:var(--shadow-md)!important;overflow:hidden!important;font-size:12px!important}',
    '#d2c-pm-hdr{padding:9px 12px!important;font-weight:700!important;font-size:11px!important;color:var(--d2c-navy)!important;border-bottom:1px solid var(--border)!important;cursor:pointer!important;user-select:none!important;text-transform:uppercase!important;letter-spacing:.5px!important;display:flex!important;align-items:center!important;justify-content:space-between!important}',
    '#d2c-pm-hdr .fa{margin-right:4px!important}',
    '#d2c-pm-widget.d2c-pm-minimized #d2c-pm-hdr{border-bottom:none!important}',
    '#d2c-pm-widget.d2c-pm-minimized #d2c-pm-body{display:none!important}',
    '#d2c-pm-body{display:flex!important;flex-direction:column!important;gap:0!important}',
    '.d2c-pm-section{border-bottom:1px solid var(--border)!important;padding:8px 10px!important}',
    '.d2c-pm-section:last-child{border-bottom:none!important}',
    '.d2c-pm-section-hdr{display:flex!important;align-items:center!important;justify-content:space-between!important;margin-bottom:5px!important}',
    '.d2c-pm-section-lbl{font-size:11px!important;font-weight:600!important;color:var(--text-muted)!important;text-transform:uppercase!important;letter-spacing:.4px!important}',
    '.d2c-pm-badge{display:inline-flex!important;align-items:center!important;justify-content:center!important;min-width:16px!important;height:16px!important;padding:0 4px!important;background:var(--border-dark)!important;color:var(--text-muted)!important;border-radius:999px!important;font-size:10px!important;font-weight:700!important;margin-left:3px!important}',
    '.d2c-pm-add-btn{padding:2px 7px!important;font-size:10px!important;font-weight:500!important;border-radius:var(--r-sm)!important;border:1px solid var(--border-dark)!important;background:var(--surface)!important;color:var(--d2c-navy)!important;cursor:pointer!important;font-family:var(--font)!important;transition:background var(--t),border-color var(--t)!important;white-space:nowrap!important}',
    '.d2c-pm-add-btn:hover{background:var(--d2c-navy)!important;border-color:var(--d2c-navy)!important;color:#fff!important}',
    /* Inline load-from-template select injected into blank promo rows */
    '.d2c-pm-load-wrap{padding:3px 6px 6px!important;box-sizing:border-box!important}',
    '.d2c-pm-load-sel{font-size:12px!important;padding:4px 8px!important;border:1px dashed #adb5bd!important;border-radius:4px!important;background:#f8f9fa!important;color:#555!important;cursor:pointer!important;width:100%!important;max-width:340px!important;font-family:inherit!important;box-sizing:border-box!important}',
    '.d2c-pm-load-sel:hover,.d2c-pm-load-sel:focus{border-color:#0a1628!important;border-style:solid!important;color:#0a1628!important;outline:none!important}',
    '.d2c-pm-list{display:flex!important;flex-direction:column!important;gap:1px!important}',
    '.d2c-pm-empty{font-size:11px!important;color:var(--text-light)!important;padding:4px 2px!important;font-style:italic!important}',
    '.d2c-pm-item{display:flex!important;align-items:center!important;gap:5px!important;padding:3px 4px!important;border-radius:var(--r-sm)!important;cursor:pointer!important;transition:background var(--t)!important;min-width:0!important}',
    '.d2c-pm-item:hover{background:var(--bg)!important}',
    '.d2c-pm-item:hover .d2c-pm-dup-btn{opacity:1!important}',
    '.d2c-pm-item-selected{background:rgba(10,33,73,.09)!important;outline:1px solid rgba(10,33,73,.3)!important}',
    '.d2c-pm-item-selected:hover{background:rgba(10,33,73,.13)!important}',
    '.d2c-pm-item-selected .d2c-pm-item-title{font-weight:600!important;color:var(--d2c-navy)!important}',
    '.d2c-pm-item-selected .d2c-pm-dup-btn{opacity:1!important}',
    '.d2c-pm-dup-btn{flex-shrink:0!important;opacity:0!important;padding:1px 4px!important;font-size:10px!important;border-radius:var(--r-sm)!important;border:1px solid transparent!important;background:none!important;color:var(--text-muted)!important;cursor:pointer!important;font-family:var(--font)!important;transition:opacity var(--t),background var(--t),color var(--t)!important;line-height:1.4!important}',
    '.d2c-pm-dup-btn:hover{background:var(--d2c-navy)!important;border-color:var(--d2c-navy)!important;color:#fff!important}',
    '.d2c-pm-dup-btn:disabled{cursor:not-allowed!important;opacity:.5!important}',
    '.d2c-pm-dot{flex-shrink:0!important;width:7px!important;height:7px!important;border-radius:50%!important;display:inline-block!important}',
    '.d2c-pm-dot-active{background:#22c55e!important}',
    '.d2c-pm-dot-expired{background:#ef4444!important}',
    '.d2c-pm-dot-upcoming{background:#f59e0b!important}',
    '.d2c-pm-item-title{flex:1!important;min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important;font-size:12px!important;color:var(--text)!important}',
    /* Accordion section toggle */
    '.d2c-pm-sec-toggle{display:flex!important;align-items:center!important;gap:4px!important;background:none!important;border:none!important;cursor:pointer!important;padding:0!important;font-family:var(--font)!important;min-width:0!important;flex:1!important}',
    '.d2c-pm-sec-arrow{font-size:9px!important;color:var(--text-muted)!important;flex-shrink:0!important;line-height:1!important}',
    '.d2c-pm-sec-collapsed .d2c-pm-list{display:none!important}',
    /* Highlight pulse on the targeted promo row */
    '@keyframes d2c-pm-pulse{0%,100%{box-shadow:inset 0 0 0 2px transparent}30%{box-shadow:inset 0 0 0 2px #f59e0b,0 0 0 3px rgba(245,158,11,.25)}}',
    'tr.d2c-pm-highlight{animation:d2c-pm-pulse 2.5s ease!important;position:relative!important}',

    /* \u2500\u2500 Promo Manager \u2014 Templates section \u2500\u2500 */
    '.d2c-pm-sec-collapsed .d2c-pm-tpl-body{display:none!important}',
    '#d2c-pm-sec-templates{border-top:2px solid var(--border-dark)!important;margin-top:2px!important}',
    '#d2c-pm-sec-templates .d2c-pm-section-hdr{padding:6px 2px 4px!important;margin-bottom:4px!important}',
    '#d2c-pm-sec-templates .d2c-pm-section-lbl{font-size:11px!important;font-weight:700!important;color:var(--d2c-navy)!important;text-transform:uppercase!important;letter-spacing:.5px!important}',
    '#d2c-pm-sec-templates .d2c-pm-badge{background:var(--d2c-navy)!important;color:#fff!important}',
    '#d2c-pm-sec-templates .d2c-pm-sec-arrow{color:var(--d2c-navy)!important}',
    '#d2c-pm-sec-templates .d2c-pm-tpl-icon{color:var(--d2c-navy)!important;margin-right:3px!important}',
    '.d2c-pm-tpl-target{font-size:11px!important;padding:3px 7px!important;border-radius:var(--r-sm)!important;background:rgba(10,33,73,.07)!important;color:var(--d2c-navy)!important;font-weight:600!important;border:1px solid rgba(10,33,73,.2)!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important}',
    '.d2c-pm-tpl-target-none{color:var(--text-muted)!important;background:var(--bg)!important;border-color:var(--border-dark)!important;font-weight:400!important;font-style:italic!important}',
    '.d2c-pm-tpl-body{display:flex!important;flex-direction:column!important;gap:6px!important;padding-top:4px!important}',
    '.d2c-pm-tpl-save-row{display:flex!important;gap:4px!important;align-items:stretch!important;flex-wrap:wrap!important}',
    '.d2c-pm-tpl-src-sel{flex:1 1 100%!important;font-size:11px!important;padding:3px 5px!important;border:1px solid var(--border-dark)!important;border-radius:var(--r-sm)!important;background:var(--surface)!important;color:var(--text)!important;cursor:pointer!important;font-family:var(--font)!important;min-width:0!important}',
    '.d2c-pm-tpl-name-input{flex:1!important;min-width:60px!important;font-size:11px!important;padding:3px 6px!important;border:1px solid var(--border-dark)!important;border-radius:var(--r-sm)!important;background:var(--surface)!important;color:var(--text)!important;font-family:var(--font)!important;outline:none!important}',
    '.d2c-pm-tpl-name-input::placeholder{color:var(--text-light)!important}',
    '.d2c-pm-tpl-name-input:focus{border-color:var(--d2c-navy)!important}',
    '.d2c-pm-tpl-btn{padding:2px 7px!important;font-size:10px!important;font-weight:500!important;border-radius:var(--r-sm)!important;border:1px solid var(--border-dark)!important;background:var(--surface)!important;color:var(--d2c-navy)!important;cursor:pointer!important;font-family:var(--font)!important;transition:background var(--t),border-color var(--t)!important;white-space:nowrap!important;flex-shrink:0!important}',
    '.d2c-pm-tpl-save{background:var(--d2c-navy)!important;color:#fff!important;border-color:var(--d2c-navy)!important}',
    '.d2c-pm-tpl-save:hover{background:#0d2040!important}',
    '.d2c-pm-tpl-list{display:flex!important;flex-direction:column!important;gap:2px!important}',
    '.d2c-pm-tpl-item{display:flex!important;align-items:center!important;gap:4px!important;padding:3px 2px!important;border-radius:var(--r-sm)!important;min-width:0!important}',
    '.d2c-pm-tpl-item:hover{background:var(--bg)!important}',
    '.d2c-pm-tpl-name{flex:1!important;min-width:0!important;overflow:hidden!important;text-overflow:ellipsis!important;white-space:nowrap!important;font-size:12px!important;color:var(--text)!important;cursor:default!important}',
    '.d2c-pm-tpl-apply{background:var(--d2c-navy)!important;color:#fff!important;border-color:var(--d2c-navy)!important}',
    '.d2c-pm-tpl-apply:hover{background:#0d2040!important}',
    '.d2c-pm-tpl-del{color:var(--text-muted)!important;padding:2px 5px!important}',
    '.d2c-pm-tpl-del:hover{background:#ef4444!important;border-color:#ef4444!important;color:#fff!important}',
    '.d2c-pm-tpl-err{background:#ef4444!important;border-color:#ef4444!important;color:#fff!important}',

    /* ── Promo Manager — Language toggle ── */
    '#d2c-pm-lang-toggle{display:flex!important;align-items:center!important;justify-content:space-between!important;padding:5px 8px!important;background:var(--surface)!important;border:1px solid var(--border)!important;border-radius:var(--r-lg)!important;box-shadow:var(--shadow-md)!important;margin-bottom:4px!important}',
    '.d2c-pm-lang-label{font-size:10px!important;font-weight:700!important;text-transform:uppercase!important;letter-spacing:.5px!important;color:var(--text-muted)!important}',
    '.d2c-pm-lang-pills{display:flex!important;gap:2px!important;background:var(--bg)!important;border-radius:var(--r-sm)!important;padding:2px!important;border:1px solid var(--border)!important}',
    '.d2c-pm-lang-btn{padding:2px 9px!important;font-size:11px!important;font-weight:600!important;border-radius:var(--r-sm)!important;border:none!important;background:transparent!important;color:var(--text-muted)!important;cursor:pointer!important;font-family:var(--font)!important;transition:all var(--t)!important;letter-spacing:.3px!important}',
    '.d2c-pm-lang-btn.d2c-pm-lang-active{background:var(--d2c-navy)!important;color:#fff!important}',
    /* Lang cell visibility — hides the inactive language column and expands the active one */
    '#page-wrapper.d2c-lang-en .d2c-lang-cell-fr{display:none!important}',
    '#page-wrapper.d2c-lang-en .d2c-lang-cell-en{width:80%!important;max-width:80%!important}',
    '#page-wrapper.d2c-lang-fr .d2c-lang-cell-en{display:none!important}',
    '#page-wrapper.d2c-lang-fr .d2c-lang-cell-fr{width:80%!important;max-width:80%!important}',

    /* ── Promo Manager — Optional field expanders ── */
    '.d2c-pm-oem-expander{padding:6px 0 5px 20%!important;line-height:1!important}',
    '.d2c-pm-oem-toggle{background:none!important;border:none!important;padding:0!important;font-size:12px!important;color:var(--text-muted)!important;cursor:pointer!important;font-family:var(--font)!important;text-decoration:underline!important;text-underline-offset:2px!important}',
    '.d2c-pm-oem-toggle:hover{color:var(--d2c-navy)!important}',

    /* ── Promo Manager — Full-screen HTML description editor ── */
    '#d2c-desc-modal{display:none!important;position:fixed!important;inset:0!important;background:rgba(0,0,0,.6)!important;z-index:10000!important;align-items:center!important;justify-content:center!important}',
    '#d2c-desc-modal.d2c-desc-modal-open{display:flex!important}',
    '#d2c-desc-modal-inner{background:#fff!important;border-radius:var(--r-lg)!important;width:90vw!important;height:90vh!important;display:flex!important;flex-direction:column!important;overflow:hidden!important;box-shadow:0 20px 60px rgba(0,0,0,.4)!important}',
    '#d2c-desc-modal-hdr{padding:12px 16px!important;border-bottom:1px solid var(--border)!important;display:flex!important;align-items:center!important;justify-content:space-between!important;flex-shrink:0!important;background:var(--surface)!important}',
    '#d2c-desc-modal-title{font-weight:700!important;font-size:13px!important;color:var(--d2c-navy)!important;letter-spacing:.3px!important}',
    '#d2c-desc-modal-close{background:none!important;border:none!important;font-size:22px!important;color:var(--text-muted)!important;cursor:pointer!important;padding:0 4px!important;line-height:1!important;font-family:inherit!important}',
    '#d2c-desc-modal-close:hover{color:#ef4444!important}',
    '#d2c-desc-modal-editor{flex:1!important;width:100%!important;border:none!important;padding:16px 20px!important;font-family:monospace!important;font-size:13px!important;line-height:1.7!important;resize:none!important;color:#1a1a1a!important;outline:none!important;box-sizing:border-box!important}',
    '.d2c-desc-expand{display:inline-block!important;background:none!important;border:none!important;font-size:16px!important;color:var(--text-muted)!important;cursor:pointer!important;padding:0!important;line-height:1!important;margin-left:5px!important;vertical-align:middle!important;font-family:inherit!important;opacity:.65!important}',
    '.d2c-desc-expand:hover{color:var(--d2c-navy)!important;opacity:1!important}',

    /* FOUC prevention — body hidden until builds complete, then fades in */
    'body.d2c-loading{opacity:0!important}',
    'body.d2c-ready{opacity:1!important;transition:opacity .25s ease!important}',

    /* Skeleton loading bar */
    '.d2c-loader-bar{position:fixed;top:0;left:0;right:0;height:3px;background:linear-gradient(90deg,var(--d2c-navy) 0%,var(--d2c-blue) 50%,var(--d2c-navy) 100%);background-size:200% 100%;animation:d2c-loader-slide 1.2s ease-in-out infinite;z-index:99999;pointer-events:none}',
    '@keyframes d2c-loader-slide{0%{background-position:200% 0}100%{background-position:-200% 0}}',
  ].join('\n');

  var styleEl = document.createElement('style');
  styleEl.id = 'd2c-custom-styles';
  styleEl.textContent = css;
  (document.head || document.documentElement).appendChild(styleEl);
}
