const esbuild = require('esbuild');
const fs = require('fs');
const isWatch = process.argv.includes('--watch');

const now = new Date();
const pad = function (n) { return String(n).padStart(2, '0'); };
const ts = now.getFullYear() + '-' +
           pad(now.getMonth() + 1) + '-' +
           pad(now.getDate()) + ' ' +
           pad(now.getHours()) + ':' +
           pad(now.getMinutes());
const banner = '/* DO NOT EDIT — generated by npm run build. Edit src/js/modules/ instead. */';

// Write the build date as a plain JS module so esbuild bundles it as a regular
// string literal — no `define` token magic that can silently fail.
fs.writeFileSync(
  'src/js/modules/build-date.js',
  '// AUTO-GENERATED by build.js — do not edit\nexport var BUILD_DATE = ' + JSON.stringify(ts) + ';\n'
);

const config = {
  entryPoints: ['src/js/modules/index.js'],
  bundle: true,
  format: 'iife',
  outfile: 'src/js/d2c-enhancements.js',
  banner: { js: banner },
};

if (isWatch) {
  esbuild.context(config).then(function (ctx) {
    ctx.watch();
    console.log('[esbuild] watching... (stamped ' + ts + ')');
  });
} else {
  esbuild.build(config)
    .then(function () { console.log('[esbuild] built → src/js/d2c-enhancements.js (' + ts + ')'); })
    .catch(function () { process.exit(1); });
}
